name: Build Cross-Platform Backend Executables

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'macos-latest']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install Windows dependencies
      if: matrix.os == 'windows-latest'
      run: |
        pip install -r requirements.txt || true
        pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu

    - name: Install MacOS dependencies
      if: matrix.os == 'macos-latest'
      run: |
        pip install -r requirements.txt || true
        pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu

    - name: Build executable
      run: |
        pyinstaller --onefile --paths . --add-data "urls.yaml:." --add-data "../../requirements.txt:." --hidden-import=models --hidden-import=utils --hidden-import=prediction --hidden-import=detection main.py
      working-directory: ./src/backend/

    - name: Create Artifact
      uses: actions/upload-artifact@v4
      with:
        name: backend-executables
        path: ./src/backend/dist/